title: "Davis Spencer Owen"
description: "Manufacturing Project Engineer | NPI | DFM/DFA | Process Development"
url: "https://dsovven.github.io"
baseurl: "/Davis-Spencer-Owen-Portfolio"
repository: "dsovven/Davis-Spencer-Owen-Portfolio"
locale: "en-US"
timezone: "America/Los_Angeles"

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: pages
    values:
      layout: page

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
